DATA INSPECTION

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/chatgpt_reviews.xlsx')
df

date                 title  \
0    2025-02-15            Impressive   
1    2024-10-16         Waste of Time   
2    2024-10-16         Waste of Time   
3    2024-12-21          Not Accurate   
4    2025-03-23  Fantastic Experience   
...         ...                   ...   
9995 2024-06-13          Very Helpful   
9996 2024-07-16                 Buggy   
9997 2024-07-22          Not Accurate   
9998 2024-05-24     Needs Improvement   
9999 2025-02-17  Fantastic Experience   

                                                 review  rating  \
0     Mother former community upon vote fact. Sure s...       2   
1     General paper understand main. Or age half won...       5   
2     Here situation his high stage. Agree certainly...       4   
3     Rule court behind growth reality. Tonight whos...       1   
4     Case opportunity season road write. Effort gre...       3   
...                                                 ...     ...   
9995  Little section hit her through. Likely job ind...       5   
9996  Throw with record relationship help reduce vot...       3   
9997  Within nothing study charge all. Toward milita...       3   
9998  Rule kitchen trouble cultural.\nDeep manage ad...       3   
9999  Resource plant behind vote its try laugh. Othe...       2   

           username  helpful_votes  review_length platform language  \
0             ybass             68             78   Mobile       es   
1           glenn33             71            193      Web       de   
2          debbie27             66            184      Web       hi   
3     hannahrussell              5            193      Web       fr   
4           cnorton             71            131      Web       hi   
...             ...            ...            ...      ...      ...   
9995         john32             30             83      Web       de   
9996      michael25             68            189   Mobile       es   
9997         sean13             10            185      Web       de   
9998         pjones             48            163   Mobile       fr   
9999  brownadrienne             61             81      Web       en   

       location  version verified_purchase  
0        Canada      3.0                No  
1         India      4.1               Yes  
2         India      4.1               Yes  
3        Canada      4.0               Yes  
4     Australia      4.1                No  
...         ...      ...               ...  
9995  Australia      3.0                No  
9996    Germany      3.5               Yes  
9997      India      3.0               Yes  
9998         UK      3.0               Yes  
9999    Germany      3.5               Yes  

[10000 rows x 12 columns]

In [ ]:
df.head()

date                 title  \
0 2025-02-15            Impressive   
1 2024-10-16         Waste of Time   
2 2024-10-16         Waste of Time   
3 2024-12-21          Not Accurate   
4 2025-03-23  Fantastic Experience   

                                              review  rating       username  \
0  Mother former community upon vote fact. Sure s...       2          ybass   
1  General paper understand main. Or age half won...       5        glenn33   
2  Here situation his high stage. Agree certainly...       4       debbie27   
3  Rule court behind growth reality. Tonight whos...       1  hannahrussell   
4  Case opportunity season road write. Effort gre...       3        cnorton   

   helpful_votes  review_length platform language   location  version  \
0             68             78   Mobile       es     Canada      3.0   
1             71            193      Web       de      India      4.1   
2             66            184      Web       hi      India      4.1   
3              5            193      Web       fr     Canada      4.0   
4             71            131      Web       hi  Australia      4.1   

  verified_purchase  
0                No  
1               Yes  
2               Yes  
3               Yes  
4                No

In [ ]:
df.shape

(10000, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   date               10000 non-null  datetime64[ns]
 1   title              10000 non-null  object        
 2   review             10000 non-null  object        
 3   rating             10000 non-null  int64         
 4   username           10000 non-null  object        
 5   helpful_votes      10000 non-null  int64         
 6   review_length      10000 non-null  int64         
 7   platform           10000 non-null  object        
 8   language           10000 non-null  object        
 9   location           10000 non-null  object        
 10  version            10000 non-null  float64       
 11  verified_purchase  10000 non-null  object        
dtypes: datetime64[ns](1), float64(1), int64(3), object(7)
memory usage: 937.6+ KB


In [ ]:
df.columns

Index(['date', 'title', 'review', 'rating', 'username', 'helpful_votes',
       'review_length', 'platform', 'language', 'location', 'version',
       'verified_purchase'],
      dtype='object')

In [ ]:
df.isnull().sum()

date                 0
title                0
review               0
rating               0
username             0
helpful_votes        0
review_length        0
platform             0
language             0
location             0
version              0
verified_purchase    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
import datetime
today=datetime.date.today()
today=pd.to_datetime(today,format='%Y-%M-%d')
print(today)

2025-05-03 00:00:00


In [ ]:
df.loc[df['date']>today]

Empty DataFrame
Columns: [date, title, review, rating, username, helpful_votes, review_length, platform, language, location, version, verified_purchase]
Index: []

In [ ]:
df['title'].value_counts()

title
Buggy                   1037
Very Helpful            1019
Waste of Time           1018
Too Slow                1016
Superb!                 1012
Great Tool!             1001
Needs Improvement        994
Fantastic Experience     984
Impressive               970
Not Accurate             949
Name: count, dtype: int64

In [ ]:
df['rating'].value_counts()

rating
1    2062
5    2013
2    2007
4    1975
3    1943
Name: count, dtype: int64

In [ ]:
df['platform'].value_counts()

platform
Mobile    5011
Web       4989
Name: count, dtype: int64

In [ ]:
df['language'].value_counts()

language
en    2016
fr    2013
de    2001
hi    1991
es    1979
Name: count, dtype: int64

In [ ]:
df['location'].value_counts()

location
Canada       1711
UK           1686
Germany      1664
India        1659
USA          1654
Australia    1626
Name: count, dtype: int64

In [ ]:
df['version'].value_counts()

version
4.1    2522
3.0    2496
4.0    2491
3.5    2491
Name: count, dtype: int64

In [ ]:
df['verified_purchase'].value_counts()

verified_purchase
No     5116
Yes    4884
Name: count, dtype: int64

DATA CLEANING AND PREPROCESSING

In [ ]:
df.drop('username', axis=1, inplace=True)

In [ ]:
df

date                 title  \
0    2025-02-15            Impressive   
1    2024-10-16         Waste of Time   
2    2024-10-16         Waste of Time   
3    2024-12-21          Not Accurate   
4    2025-03-23  Fantastic Experience   
...         ...                   ...   
9995 2024-06-13          Very Helpful   
9996 2024-07-16                 Buggy   
9997 2024-07-22          Not Accurate   
9998 2024-05-24     Needs Improvement   
9999 2025-02-17  Fantastic Experience   

                                                 review  rating  \
0     Mother former community upon vote fact. Sure s...       2   
1     General paper understand main. Or age half won...       5   
2     Here situation his high stage. Agree certainly...       4   
3     Rule court behind growth reality. Tonight whos...       1   
4     Case opportunity season road write. Effort gre...       3   
...                                                 ...     ...   
9995  Little section hit her through. Likely job ind...       5   
9996  Throw with record relationship help reduce vot...       3   
9997  Within nothing study charge all. Toward milita...       3   
9998  Rule kitchen trouble cultural.\nDeep manage ad...       3   
9999  Resource plant behind vote its try laugh. Othe...       2   

      helpful_votes  review_length platform language   location  version  \
0                68             78   Mobile       es     Canada      3.0   
1                71            193      Web       de      India      4.1   
2                66            184      Web       hi      India      4.1   
3                 5            193      Web       fr     Canada      4.0   
4                71            131      Web       hi  Australia      4.1   
...             ...            ...      ...      ...        ...      ...   
9995             30             83      Web       de  Australia      3.0   
9996             68            189   Mobile       es    Germany      3.5   
9997             10            185      Web       de      India      3.0   
9998             48            163   Mobile       fr         UK      3.0   
9999             61             81      Web       en    Germany      3.5   

     verified_purchase  
0                   No  
1                  Yes  
2                  Yes  
3                  Yes  
4                   No  
...                ...  
9995                No  
9996               Yes  
9997               Yes  
9998               Yes  
9999               Yes  

[10000 rows x 11 columns]

In [ ]:
!pip install langdetect

In [ ]:
from langdetect import detect
from tqdm import tqdm
tqdm.pandas()
df['detected_language'] = df['review'].progress_apply(lambda x: detect(x) if isinstance(x, str) and x.strip() else "unknown")
print(df['detected_language'].value_counts())

100%|██████████| 10000/10000 [00:42<00:00, 233.79it/s]

detected_language
en    9987
fr       6
nl       2
no       1
de       1
it       1
ro       1
da       1
Name: count, dtype: int64


In [ ]:
df = df[df['detected_language'] == 'en'].reset_index(drop=True)

In [ ]:
df

date                 title  \
0    2025-02-15            Impressive   
1    2024-10-16         Waste of Time   
2    2024-10-16         Waste of Time   
3    2024-12-21          Not Accurate   
4    2025-03-23  Fantastic Experience   
...         ...                   ...   
9982 2024-06-13          Very Helpful   
9983 2024-07-16                 Buggy   
9984 2024-07-22          Not Accurate   
9985 2024-05-24     Needs Improvement   
9986 2025-02-17  Fantastic Experience   

                                                 review  rating  \
0     Mother former community upon vote fact. Sure s...       2   
1     General paper understand main. Or age half won...       5   
2     Here situation his high stage. Agree certainly...       4   
3     Rule court behind growth reality. Tonight whos...       1   
4     Case opportunity season road write. Effort gre...       3   
...                                                 ...     ...   
9982  Little section hit her through. Likely job ind...       5   
9983  Throw with record relationship help reduce vot...       3   
9984  Within nothing study charge all. Toward milita...       3   
9985  Rule kitchen trouble cultural.\nDeep manage ad...       3   
9986  Resource plant behind vote its try laugh. Othe...       2   

      helpful_votes  review_length platform language   location  version  \
0                68             78   Mobile       es     Canada      3.0   
1                71            193      Web       de      India      4.1   
2                66            184      Web       hi      India      4.1   
3                 5            193      Web       fr     Canada      4.0   
4                71            131      Web       hi  Australia      4.1   
...             ...            ...      ...      ...        ...      ...   
9982             30             83      Web       de  Australia      3.0   
9983             68            189   Mobile       es    Germany      3.5   
9984             10            185      Web       de      India      3.0   
9985             48            163   Mobile       fr         UK      3.0   
9986             61             81      Web       en    Germany      3.5   

     verified_purchase detected_language  
0                   No                en  
1                  Yes                en  
2                  Yes                en  
3                  Yes                en  
4                   No                en  
...                ...               ...  
9982                No                en  
9983               Yes                en  
9984               Yes                en  
9985               Yes                en  
9986               Yes                en  

[9987 rows x 12 columns]

In [ ]:
%pip install vaderSentiment

In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Initialize the VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# Function to get VADER sentiment (positive, negative, neutral)
def get_vader_sentiment(text):
    score = analyzer.polarity_scores(text)
    if score['compound'] >= 0.05:
        return 'positive'
    elif score['compound'] <= -0.05:
        return 'negative'
    else:
        return 'neutral'

# Apply VADER sentiment to the review text
df['vader_sentiment'] = df['review'].apply(get_vader_sentiment)

# Adjust sentiment based on rating
def adjust_sentiment_based_on_rating(row):
    if row['rating'] >= 4:
        return 'positive'
    elif row['rating'] <= 2:
        return 'negative'
    else:
        return 'neutral'

df['adjusted_sentiment'] = df.apply(adjust_sentiment_based_on_rating, axis=1)

# Combine VADER sentiment with adjusted sentiment (rating-based)
df['final_sentiment'] = df.apply(lambda row: row['adjusted_sentiment'] if row['vader_sentiment'] == 'neutral' else row['vader_sentiment'], axis=1)

In [ ]:
df

date                 title  \
0    2025-02-15            Impressive   
1    2024-10-16         Waste of Time   
2    2024-10-16         Waste of Time   
3    2024-12-21          Not Accurate   
4    2025-03-23  Fantastic Experience   
...         ...                   ...   
9982 2024-06-13          Very Helpful   
9983 2024-07-16                 Buggy   
9984 2024-07-22          Not Accurate   
9985 2024-05-24     Needs Improvement   
9986 2025-02-17  Fantastic Experience   

                                                 review  rating  \
0     Mother former community upon vote fact. Sure s...       2   
1     General paper understand main. Or age half won...       5   
2     Here situation his high stage. Agree certainly...       4   
3     Rule court behind growth reality. Tonight whos...       1   
4     Case opportunity season road write. Effort gre...       3   
...                                                 ...     ...   
9982  Little section hit her through. Likely job ind...       5   
9983  Throw with record relationship help reduce vot...       3   
9984  Within nothing study charge all. Toward milita...       3   
9985  Rule kitchen trouble cultural.\nDeep manage ad...       3   
9986  Resource plant behind vote its try laugh. Othe...       2   

      helpful_votes  review_length platform language   location  version  \
0                68             78   Mobile       es     Canada      3.0   
1                71            193      Web       de      India      4.1   
2                66            184      Web       hi      India      4.1   
3                 5            193      Web       fr     Canada      4.0   
4                71            131      Web       hi  Australia      4.1   
...             ...            ...      ...      ...        ...      ...   
9982             30             83      Web       de  Australia      3.0   
9983             68            189   Mobile       es    Germany      3.5   
9984             10            185      Web       de      India      3.0   
9985             48            163   Mobile       fr         UK      3.0   
9986             61             81      Web       en    Germany      3.5   

     verified_purchase detected_language vader_sentiment adjusted_sentiment  \
0                   No                en        positive           negative   
1                  Yes                en        positive           positive   
2                  Yes                en        positive           positive   
3                  Yes                en        positive           negative   
4                   No                en        negative            neutral   
...                ...               ...             ...                ...   
9982                No                en         neutral           positive   
9983               Yes                en        positive            neutral   
9984               Yes                en        positive            neutral   
9985               Yes                en        positive            neutral   
9986               Yes                en        positive           negative   

     final_sentiment  
0           positive  
1           positive  
2           positive  
3           positive  
4           negative  
...              ...  
9982        positive  
9983        positive  
9984        positive  
9985        positive  
9986        positive  

[9987 rows x 15 columns]

In [ ]:
!pip install emoji

In [ ]:
#EMOJI TO TEXT
import emoji
df['review']=df['review'].apply(emoji.demojize)
df['title']=df['title'].apply(emoji.demojize)

In [ ]:
df['review']=df['review'].str.lower()
df['review']=df['review'].str.replace(r"http\S+|www\S+|https\S+", "", regex=True)
df['review']=df['review'].str.replace(r"@\w+|\#", "", regex=True)
df['review']=df['review'].str.replace(r"\d+", "", regex=True)
df['review']=df['review'].str.replace(r"[^\w\s]", "", regex=True)
df['review']=df['review'].str.replace(r"\s+", " ", regex=True).str.strip()

In [ ]:
df['title']=df['title'].str.lower()
df['title']=df['title'].str.replace(r"http\S+|www\S+|https\S+", "", regex=True)
df['title']=df['title'].str.replace(r"@\w+|\#", "", regex=True)
df['title']=df['title'].str.replace(r"\d+", "", regex=True)
df['title']=df['title'].str.replace(r"[^\w\s]", "", regex=True)
df['title']=df['title'].str.replace(r"\s+", " ", regex=True).str.strip()

In [ ]:
#TOKENIZATION
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')
df['review']=df['review'].apply(word_tokenize)
df['title']=df['title'].apply(word_tokenize)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [ ]:
df

date                    title  \
0    2025-02-15             [impressive]   
1    2024-10-16        [waste, of, time]   
2    2024-10-16        [waste, of, time]   
3    2024-12-21          [not, accurate]   
4    2025-03-23  [fantastic, experience]   
...         ...                      ...   
9982 2024-06-13          [very, helpful]   
9983 2024-07-16                  [buggy]   
9984 2024-07-22          [not, accurate]   
9985 2024-05-24     [needs, improvement]   
9986 2025-02-17  [fantastic, experience]   

                                                 review  rating  \
0     [mother, former, community, upon, vote, fact, ...       2   
1     [general, paper, understand, main, or, age, ha...       5   
2     [here, situation, his, high, stage, agree, cer...       4   
3     [rule, court, behind, growth, reality, tonight...       1   
4     [case, opportunity, season, road, write, effor...       3   
...                                                 ...     ...   
9982  [little, section, hit, her, through, likely, j...       5   
9983  [throw, with, record, relationship, help, redu...       3   
9984  [within, nothing, study, charge, all, toward, ...       3   
9985  [rule, kitchen, trouble, cultural, deep, manag...       3   
9986  [resource, plant, behind, vote, its, try, laug...       2   

      helpful_votes  review_length platform language   location  version  \
0                68             78   Mobile       es     Canada      3.0   
1                71            193      Web       de      India      4.1   
2                66            184      Web       hi      India      4.1   
3                 5            193      Web       fr     Canada      4.0   
4                71            131      Web       hi  Australia      4.1   
...             ...            ...      ...      ...        ...      ...   
9982             30             83      Web       de  Australia      3.0   
9983             68            189   Mobile       es    Germany      3.5   
9984             10            185      Web       de      India      3.0   
9985             48            163   Mobile       fr         UK      3.0   
9986             61             81      Web       en    Germany      3.5   

     verified_purchase detected_language vader_sentiment adjusted_sentiment  \
0                   No                en        positive           negative   
1                  Yes                en        positive           positive   
2                  Yes                en        positive           positive   
3                  Yes                en        positive           negative   
4                   No                en        negative            neutral   
...                ...               ...             ...                ...   
9982                No                en         neutral           positive   
9983               Yes                en        positive            neutral   
9984               Yes                en        positive            neutral   
9985               Yes                en        positive            neutral   
9986               Yes                en        positive           negative   

     final_sentiment  
0           positive  
1           positive  
2           positive  
3           positive  
4           negative  
...              ...  
9982        positive  
9983        positive  
9984        positive  
9985        positive  
9986        positive  

[9987 rows x 15 columns]

In [ ]:
%pip install pyspellchecker

In [ ]:
from spellchecker import SpellChecker
spell = SpellChecker()
def spell_check(text):
  result = []
  for word in text:
    correct_word = spell.correction(word)
    result.append(correct_word)
  return result

df['review'] = df['review'].apply(spell_check)
df['title']=df['title'].apply(spell_check)

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def remove_stopwords(tokens):
  return [word for word in tokens if word not in stop_words]

df['review'] = df['review'].apply(remove_stopwords)
df['title']=df['title'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
df

date                    title  \
0    2025-02-15             [impressive]   
1    2024-10-16            [waste, time]   
2    2024-10-16            [waste, time]   
3    2024-12-21               [accurate]   
4    2025-03-23  [fantastic, experience]   
...         ...                      ...   
9982 2024-06-13                [helpful]   
9983 2024-07-16                  [buggy]   
9984 2024-07-22               [accurate]   
9985 2024-05-24     [needs, improvement]   
9986 2025-02-17  [fantastic, experience]   

                                                 review  rating  \
0     [mother, former, community, upon, vote, fact, ...       2   
1     [general, paper, understand, main, age, half, ...       5   
2     [situation, high, stage, agree, certainly, blu...       4   
3     [rule, court, behind, growth, reality, tonight...       1   
4     [case, opportunity, season, road, write, effor...       3   
...                                                 ...     ...   
9982  [little, section, hit, likely, job, indicate, ...       5   
9983  [throw, record, relationship, help, reduce, vo...       3   
9984  [within, nothing, study, charge, toward, milit...       3   
9985  [rule, kitchen, trouble, cultural, deep, manag...       3   
9986  [resource, plant, behind, vote, try, laugh, ot...       2   

      helpful_votes  review_length platform language   location  version  \
0                68             78   Mobile       es     Canada      3.0   
1                71            193      Web       de      India      4.1   
2                66            184      Web       hi      India      4.1   
3                 5            193      Web       fr     Canada      4.0   
4                71            131      Web       hi  Australia      4.1   
...             ...            ...      ...      ...        ...      ...   
9982             30             83      Web       de  Australia      3.0   
9983             68            189   Mobile       es    Germany      3.5   
9984             10            185      Web       de      India      3.0   
9985             48            163   Mobile       fr         UK      3.0   
9986             61             81      Web       en    Germany      3.5   

     verified_purchase detected_language vader_sentiment adjusted_sentiment  \
0                   No                en        positive           negative   
1                  Yes                en        positive           positive   
2                  Yes                en        positive           positive   
3                  Yes                en        positive           negative   
4                   No                en        negative            neutral   
...                ...               ...             ...                ...   
9982                No                en         neutral           positive   
9983               Yes                en        positive            neutral   
9984               Yes                en        positive            neutral   
9985               Yes                en        positive            neutral   
9986               Yes                en        positive           negative   

     final_sentiment  
0           positive  
1           positive  
2           positive  
3           positive  
4           negative  
...              ...  
9982        positive  
9983        positive  
9984        positive  
9985        positive  
9986        positive  

[9987 rows x 15 columns]

In [ ]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def lemmatize_text(tokens):
  return [lemmatizer.lemmatize(word) for word in tokens]
df['review'] = df['review'].apply(lemmatize_text)
df['title']=df['title'].apply(lemmatize_text)

In [ ]:
df.to_excel("/content/drive/My Drive/cleaned_chatgpt_reviews.xlsx", index=False)

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/My Drive/cleaned_chatgpt_reviews.xlsx')
df

date                        title  \
0    2025-02-15               ['impressive']   
1    2024-10-16            ['waste', 'time']   
2    2024-10-16            ['waste', 'time']   
3    2024-12-21                 ['accurate']   
4    2025-03-23  ['fantastic', 'experience']   
...         ...                          ...   
9982 2024-06-13                  ['helpful']   
9983 2024-07-16                    ['buggy']   
9984 2024-07-22                 ['accurate']   
9985 2024-05-24      ['need', 'improvement']   
9986 2025-02-17  ['fantastic', 'experience']   

                                                 review  rating  \
0     ['mother', 'former', 'community', 'upon', 'vot...       2   
1     ['general', 'paper', 'understand', 'main', 'ag...       5   
2     ['situation', 'high', 'stage', 'agree', 'certa...       4   
3     ['rule', 'court', 'behind', 'growth', 'reality...       1   
4     ['case', 'opportunity', 'season', 'road', 'wri...       3   
...                                                 ...     ...   
9982  ['little', 'section', 'hit', 'likely', 'job', ...       5   
9983  ['throw', 'record', 'relationship', 'help', 'r...       3   
9984  ['within', 'nothing', 'study', 'charge', 'towa...       3   
9985  ['rule', 'kitchen', 'trouble', 'cultural', 'de...       3   
9986  ['resource', 'plant', 'behind', 'vote', 'try',...       2   

      helpful_votes  review_length platform language   location  version  \
0                68             78   Mobile       es     Canada      3.0   
1                71            193      Web       de      India      4.1   
2                66            184      Web       hi      India      4.1   
3                 5            193      Web       fr     Canada      4.0   
4                71            131      Web       hi  Australia      4.1   
...             ...            ...      ...      ...        ...      ...   
9982             30             83      Web       de  Australia      3.0   
9983             68            189   Mobile       es    Germany      3.5   
9984             10            185      Web       de      India      3.0   
9985             48            163   Mobile       fr         UK      3.0   
9986             61             81      Web       en    Germany      3.5   

     verified_purchase detected_language vader_sentiment adjusted_sentiment  \
0                   No                en        positive           negative   
1                  Yes                en        positive           positive   
2                  Yes                en        positive           positive   
3                  Yes                en        positive           negative   
4                   No                en        negative            neutral   
...                ...               ...             ...                ...   
9982                No                en         neutral           positive   
9983               Yes                en        positive            neutral   
9984               Yes                en        positive            neutral   
9985               Yes                en        positive            neutral   
9986               Yes                en        positive           negative   

     final_sentiment  
0           positive  
1           positive  
2           positive  
3           positive  
4           negative  
...              ...  
9982        positive  
9983        positive  
9984        positive  
9985        positive  
9986        positive  

[9987 rows x 15 columns]

In [ ]:
df_copy=df.copy()

In [ ]:
df_copy['adjusted_sentiment'].value_counts()

adjusted_sentiment
negative    4064
positive    3983
neutral     1940
Name: count, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
title_vectorizer = TfidfVectorizer(max_features=5000)
review_vectorizer = TfidfVectorizer(max_features=5000)

title_features = title_vectorizer.fit_transform(df_copy['title'])
review_features = review_vectorizer.fit_transform(df_copy['review'])

# Include rating as a feature (normalize it)
rating_feature = df_copy['rating'].values.reshape(-1, 1)

In [ ]:
df_copy['final_sentiment'] = df_copy['final_sentiment'].map({'positive': 2, 'negative': 0, 'neutral': 1})

In [ ]:
df_copy['adjusted_sentiment'] = df_copy['adjusted_sentiment'].map({'positive': 2, 'negative': 0, 'neutral': 1})

In [ ]:
df_copy['vader_sentiment'] = df_copy['vader_sentiment'].map({'positive': 2, 'negative': 0, 'neutral': 1})

In [ ]:
from scipy.sparse import hstack
# Now, stack horizontally
#X = hstack([title_features, review_features, rating_feature])
X = review_features
y = df_copy['final_sentiment']

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

smote = SMOTE(sampling_strategy='auto', random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Train-test split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, stratify=y_resampled, random_state=42)

# Initialize Logistic Regression with class weight adjustment
model = LogisticRegression(class_weight='balanced', max_iter=1000)

# Train the model on the resampled data
model.fit(X_resampled, y_resampled)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.93      0.92      1501
           1       0.95      1.00      0.97      1501
           2       0.95      0.88      0.91      1501

    accuracy                           0.94      4503
   macro avg       0.94      0.94      0.94      4503
weighted avg       0.94      0.94      0.94      4503

Confusion Matrix:
[[1397   33   71]
 [   0 1501    0]
 [ 127   51 1323]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(class_weight='balanced', random_state=42)
rf_model.fit(X_resampled, y_resampled)
y_pred_rf = rf_model.predict(X_test)

print("Random Forest:")
print(classification_report(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))

Random Forest:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1501
           1       1.00      1.00      1.00      1501
           2       1.00      1.00      1.00      1501

    accuracy                           1.00      4503
   macro avg       1.00      1.00      1.00      4503
weighted avg       1.00      1.00      1.00      4503

[[1501    0    0]
 [   0 1501    0]
 [   0    0 1501]]


In [ ]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(scale_pos_weight=1, use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_resampled, y_resampled)
y_pred_xgb = xgb_model.predict(X_test)

print("XGBoost:")
print(classification_report(y_test, y_pred_xgb))
print(confusion_matrix(y_test, y_pred_xgb))

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [16:56:29] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "scale_pos_weight", "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBoost:
              precision    recall  f1-score   support

           0       1.00      0.94      0.97      1501
           1       1.00      0.99      0.99      1501
           2       0.94      1.00      0.97      1501

    accuracy                           0.98      4503
   macro avg       0.98      0.98      0.98      4503
weighted avg       0.98      0.98      0.98      4503

[[1417    0   84]
 [   0 1486   15]
 [   5    0 1496]]


In [ ]:
from xgboost import XGBClassifier
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Compute class weights
classes = np.unique(y_resampled)
class_weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_resampled)
class_weights_dict = {i: w for i, w in zip(classes, class_weights)}

# Set scale_pos_weight indirectly using sample weights
sample_weights = [class_weights_dict[label] for label in y_resampled]

xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_resampled, y_resampled, sample_weight=sample_weights)
y_pred_xgb = xgb_model.predict(X_test)

print("XGBoost with Class Weights:")
print(classification_report(y_test, y_pred_xgb, zero_division=0))


/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [16:59:20] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBoost with Class Weights:
              precision    recall  f1-score   support

           0       1.00      0.94      0.97      1501
           1       1.00      0.99      0.99      1501
           2       0.94      1.00      0.97      1501

    accuracy                           0.98      4503
   macro avg       0.98      0.98      0.98      4503
weighted avg       0.98      0.98      0.98      4503



In [ ]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()
nb_model.fit(X_resampled, y_resampled)
y_pred_nb = nb_model.predict(X_test)

print("Multinomial Naive Bayes:")
print(classification_report(y_test, y_pred_nb))
print(confusion_matrix(y_test, y_pred_nb))

Multinomial Naive Bayes:
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1501
           1       0.93      0.94      0.93      1501
           2       0.91      0.85      0.88      1501

    accuracy                           0.89      4503
   macro avg       0.90      0.89      0.89      4503
weighted avg       0.90      0.89      0.89      4503

[[1346   54  101]
 [  70 1407   24]
 [ 178   48 1275]]
